language: go
go:
- 1.8.x

before_install:
- go get github.com/mitchellh/gox

install:
- go get github.com/mitchellh/mapstructure
- go get github.com/op/go-logging
- go get github.com/spf13/cobra
- go get github.com/spf13/viper
- go get github.com/oscp/openshift-monitoring-checks/checks

script:
- gox -osarch="linux/amd64" -output "./dist/{{.Dir}}" github.com/oscp/openshift-monitoring-cli
- tar -zcvf ose-mon-cli.tar.gz dist

deploy:
  provider: releases
  api_key:
    secure: CbO5hou3FCTx/fZHnRuOuVN4xBhlcz4Wt1RlwP9HR0h4Gop9WDNQ+f/llvh7i3M1/0WdGw8/uxObL/NAQ+TMy0GTF0gaEt1spnrlyp+xE02OF1HGcJV/PAsZbpyyY7GYOS+uSJ221OY2J9rYCgYticVMW+q0ZVvI27bQs0jmVh8+pDxvw85vZIW9nyVImKSODvSXpfx9QnmZMFRlnbyO9w0jVR236Ux5e7ADozEYvJsFzElgMLCJ7tO8bsT7blF74JwkaI82tffppmKRxcASwS93xLdBqLntOQJbqD5Pgle40hO73Z6I06wTSmjY7+Jb4x5btkjiyNRWh4EgIqtBsuFdhwNpCA1akjBdlIVPQ6chByF2MJbarUJqkZwdMgHpq7PcUnEQF1X0ikzKQexULV0OLuIhsrpFpHTD3f0VP+cYn1bpm3RvT2QjjzcUgx3EQSiVX98iag+2GSkTYw8Gwt3lSAWbO7UzKdkhegI4T8/Yygwevdri1DM+bqPtRPJDtgPbNjjIH0oxHP1FIZX2WfAIuz0+lx0kAGccD0Xff98neXs0f2DTXEB5dTop8l3LyeyDqXnZJLbQmIvbp0Ox4camydvi6vrL8rEc+dTv1Cmw3A2kun0Oc94jNOncx0BsS2myIuQ22yJOOJEaKDZ3IJ1ZXbYGZzVSR6u85+I96BM=
  file: ose-mon-cli.tar.gz
  skip_cleanup: true
  on:
    tags: true
    
