node:
  type: <node|master|storage>
logging:
  level: <info|debug>
etcd:
  ips: <https://ip:port>,<https://ip:port>,<https://ip:port>
registry:
  ip: <ip>
router:
  ips: <ip>,<ip>
externalSystemUrl: <https://url>
hawcularIP: <ip>
projectsWithoutLimits: <integer>
certs:
  minorDays: 60
  majorDays: 30
  paths:
    master:
      - <path1>
      - <path2>
    node:
      - <path1>
      - <path2>